### ISSUE TITLE
Bootstrap Design

### ISSUE THREAD

**Issue by BenSto** [kjoscha/Zukunftsstudie#12]
Was mir gerade aufgefallen ist, als ich die Seite auf dem Laptop gesehen habe ist:
1. Das Bild mit dem transparenten Rucksackträger ist nicht responsiv, sprich es ist zu groß und liegt dann über der Webseite. Oder sagen wir knallhart, dass die Seite nur für den Desktop gebaut ist (denke das könnte etwas problematisch werden, Laptop sollte schon (meiner Meinung nach) mit drin sein)  @mahoma511 
2. Das zweite Bild (felsiger Strand) ist noch das Bild aus dem original Grayscale Schema, soll das so bleiben oder nehmen wir das Bild sowie wie das Kontaktformular eh noch raus?

**Comment by kjoscha** [comment]
>Das Bild mit dem transparenten Rucksackträger ist nicht responsiv, sprich es ist zu groß und liegt dann über der Webseite. Oder sagen wir knallhart, dass die Seite nur für den Desktop gebaut ist (denke das könnte etwas problematisch werden, Laptop sollte schon (meiner Meinung nach) mit drin sein) @mahoma511 

was hast du denn für einen Browser? Bei mir und Mahoma funktioniert alles wie gewollt

**Comment by mahoma511** [comment]
Ich hab es gerade auf nem iPad getestet. ich glaube ich weiß was du meinst. 
Die Seite ist responsive und das Bild ist auch nicht zu groß, aber das Jscript für die collapsing Navbar funktioniert auf kleinen Auflösungen wohl nicht richtig.

 // jQuery to collapse the navbar on scroll

function collapseNavbar() {
    if ($(".navbar").offset().top > 50) {
        $(".navbar-fixed-top").addClass("top-nav-collapse");
    } else {
        $(".navbar-fixed-top").removeClass("top-nav-collapse");
    }
} 

Wenn man wieder ganz nach oben scrollt und dann runter, gibt es den Fehler, dass die Navbar durchsichtig ist (Startposition). Wenn sich das nicht auf die schnelle beheben lässt, kann man das erstmal für die Präsi rauslassen.
