### ISSUE TITLE
Javascript Beispielsammlung

### ISSUE THREAD

**Issue by kjoscha** [kjoscha/Zukunftsstudie#2]
Einfachstes Beispiel: http://bl.ocks.org/jose187/4733747
Ähnlichl: http://jansipke.nl/creating-network-diagrams-with-d3-js/
Aufwändiger mit Tutorial: http://flowingdata.com/2012/08/02/how-to-make-an-interactive-network-visualization/

**Comment by BenSto** [comment]
Ich habe mit vis.js noch  nichts gemacht. Ist aber MIT Lizenz und sieht auch passend für unseren Zweck aus.
http://visjs.org/network_examples.html

**Comment by kjoscha** [comment]
Habe es mir angeschaut und finde ich super! Ich würde mal einen kleines Anfangsbeispiel aufsetzen, okay?

**Comment by 00Bock** [comment]
circularImages

**Comment by kjoscha** [comment]
Es gibt nun ein kleines Beispiel im Master. Einfach index.html mit einem Browser öffnen.

**Comment by BenSto** [comment]
> Es gibt nun ein kleines Beispiel im Master. Einfach index.html mit einem Browser öffnen.

Top!!

**Comment by BenSto** [comment]
Da sich vis.js ja bewährt hat, denke ich das wir das Issue closen können. --> closed
