### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by kjoscha** [kjoscha/Zukunftsstudie#7]
Also ein Anfang ist ja bereits gemacht. Ich würde mich auch weiterhin mit den interaktiven Grafiken auseinandersetzen.
@mahoma511 Ihr gestaltet dann das Webseiten-Layout rumherum? Also so etwas wie Navbar, Infotext etc.? Der Anfang in Github ist sicherlich nicht ganz so easy - wenn ihr Fragen dazu habt bzw. Hilfe braucht, kommt gerne vorbei...

**Comment by super-helgi** [comment]
@kjoscha ,
ich fahre gleich los zum Campen und bin erst am Montag wieder in Berlin (dann auch nur für einen Tag, weil ich am Mittwoch wieder weg bin). Ich habe hier noch mal bei der Einstiegsseite den Text etwas geändert und hier als txt-Datei angefügt...sicherheitshalber sende ich sie noch mal per Mail als html.
Dann also erst mal schöne Pfingsten!!! wünscht Helga
[20160513 ZF home.txt](https://github.com/kjoscha/Zukunftsstudie/files/263246/20160513.ZF.home.txt)

**Comment by super-helgi** [comment]
Aha. Wenn ich das "close", kann man nicht mehr direkt antworten...

**Comment by kjoscha** [comment]
ok, alle Änderungen und ID1081 online

**Comment by kjoscha** [comment]
`<html>`

**Comment by kjoscha** [comment]
So, 'Partizipative Mobilitäts-Plattformen' ist jetzt auch drin...

**Comment by super-helgi** [comment]
Toll!!! Danke - sieht ja alles schon mal prima aus!

**Comment by kjoscha** [comment]
achso, ich habe es jetzt so gebaut, dass die Höhe des Mainstream-Bereichs dynamisch ist, also eingestellt werden kann. Also Bescheid geben, falls er irgendwo größer oder kleiner sein soll...

**Comment by kjoscha** [comment]
mahoma hat das neue Design fertiggestellt. Ich habe es eingebaut und die Grafiken entsprechend etwas farblich angepasst...

**Comment by super-helgi** [comment]
Wow, sieht das toll aus!!!

**Comment by BenSto** [comment]
Ich denke das spezifische Issue des Layouts kann dann auch erstmal geschlossen werden, ansonsten soll er/sie sich melden oder für immer schweigen ;-) bzw einfach reopen. Danke. --> closed.

btw ick finds auch sehr ansprechend :+1:
