### ISSUE TITLE
Popup-Content

### ISSUE THREAD

**Issue by kjoscha** [kjoscha/Zukunftsstudie#8]
So, diese Issue sammeln wir nun einfach mal, um Content für die PopUps zu sammeln. @super-helgi

**Comment by kjoscha** [comment]
Beispiel:
```
<p style='text-align: center;'>
  <img src='img/Spurhalten.png' width='100%'></img>
</p>
<p>
  <html>
    <head>
    </head>
    <body>
</body>
</html>
</p>
<p>
  <title></title>
</p>
<h2>
  <b>Roadmap Automatisierung</b>
</h2>
<ul>
  <li>
    <strong>1960-1990</strong>: Tempomat, ABS, Antriebsschlupfregelung
  </li>
  <li>
    <strong>1990-2000</strong>: Elektronisches Stabilit&auml;tsprogramm, Bremsassistent, Spurverlassenswarner, Adaptive Cruise Control
  </li>
  <li>
    <strong>2000-2010</strong>: Spurhalteassistent, Totwinkel&uuml;berwachung, Parklenkassistent, Adaptives Kurvenlicht, Verkehrszeichenerkennung, Automatisches Notbremsen
  </li>
  <li>
    <strong>2010-202</strong>0: Parkman&ouml;verassistent, Stauassistent, Schl&uuml;sselparken, Staufolgefahren (Fahren im Stau), Valet Parking (Fahrerloses Parken)
  </li>
</ul>
<p>
  <span style="font-size:12px;">(Quelle: www.auto-motor-und-sport.de/news/assistenzsysteme-spurhalteassistent-zum-nachruesten-1003103.html)</span>
</p>
<p style="text-align: center;">
  <a href="http://innoz.de">mehr Informationen &gt;&gt;&gt;</a><a> </a>
</p>
<p>
  <a> </a><a> </a>
</p>
```

**Comment by kjoscha** [comment]
@super-helgi kleine Info, die ID findest du nach dem Klicken nun unten neben dem Position-Export-Button. Es gibt auch ein kleines Design-Update: Alle Punkte mit Content werden nun mit einem Info-Icon angezeigt...

**Comment by super-helgi** [comment]
@kjoscha 
hier wäre noch mal Text für die (neue) ID 1081:

<p style='text-align: center;'>
  <img src='img/Spurhalten.png' width='100%'></img>
</p>
<p>
  <html>
    <head>
    </head>
    <body>
</body>
</html>
</p>
<p>
  <title></title>
</p>
<h2>
  <b>Autonome Elektro-Autos</b>
</h2>
<body>
		<ul>
			<li style="margin-left: 0.25in;">
				<strong>2011</strong>: General Motors entwickelt den EN-V (Electric Networked Vehicle) als autonomes e-Auto.</li>
			<li style="margin-left: 0.25in;">
				<strong>2010</strong>: Das VisLab der Universit&auml;t Parma hat im Rahmen des VisLab Intercontinental Autonomous Challenge (VIAC) vier autonome elektrische Vans &uuml;ber fast 16.000 km von Parma bis zur Expo in Shanghai fahren lassen.</li>
			<li style="margin-left: 0.25in;">
				<strong>2013</strong>: Nissan hat den Leaf zu einem autonom fahrenden Prototypen umgebaut.</li>
			<li style="margin-left: 0.25in;">
				<strong>2014</strong>: Induct Technology bringt den Acht-Sitzer &ldquo;Navia Shuttle&rdquo; als erstes kommerziell erh&auml;ltliches selbstfahrendes Fahrzeug auf den Markt.</li>
			<li style="margin-left: 0.25in;">
				<strong>2016</strong>: Tesla stattet seit 2014 die S-Klasse mit dem &ldquo;Autopiloten&rdquo; aus, der seit Januar 2016 ein autonomes Einparken ohne Fahrer erlaubt.</li>
		</ul>
	</body>
<p>
  <span style="font-size:12px;">(Quelle: Wikipedia; http://i.telegraph.co.uk/multimedia/archive/02789/Navia-shuttle_2789447b.jpg, http://viac.vislab.it)</span>
</p>
<p style="text-align: center;">
  <a href="http://innoz.de">mehr Informationen &gt;&gt;&gt;</a><a> </a>
</p>
<p>
  <a> </a><a> </a>
</p>

**Comment by super-helgi** [comment]
Hhhhmmm, das sieht hier jetzt aber anders aus als im HTML-Editor...ich frag Dich morgen noch mal, ob das in dem Format oben so passt!

**Comment by kjoscha** [comment]
>Hhhhmmm, das sieht hier jetzt aber anders aus als im HTML-Editor...ich frag Dich morgen noch mal, ob das in dem Format oben so passt!

ja , du musst mir den HTMl-Code davon schicken wie beim letzten Mal. Im Editor gibts dafür oben links den "Source"-Button...

**Comment by kjoscha** [comment]
i see... GithHub hat selbst versucht, den HTML-Code zu übersetzen. Ich kann den HTML-Code aber sehen, wenn ich auf bearbeiten gehe. Um das zu verhindern, kannst du hier oben  auf das "Insert Code"-Symbol "<>" klicken und das HTML da reinkopieren...

**Comment by kjoscha** [comment]
ID1081:

```
<p style='text-align: center;'>
  <img src='img/navia shuttle.png' width='100%'></img>
</p>
<p>
  <html>
    <head>
    </head>
    <body>
</body>
</html>
</p>
<p>
  <title></title>
</p>
<h2>
  <b>Autonome Elektro-Autos</b>
</h2>
<body>
		<ul>
			<li style="margin-left: 0.25in;">
				<strong>2011</strong>: General Motors entwickelt den EN-V (Electric Networked Vehicle) als autonomes e-Auto.</li>
			<li style="margin-left: 0.25in;">
				<strong>2010</strong>: Das VisLab der Universit&auml;t Parma hat im Rahmen des VisLab Intercontinental Autonomous Challenge (VIAC) vier autonome elektrische Vans &uuml;ber fast 16.000 km von Parma bis zur Expo in Shanghai fahren lassen.</li>
			<li style="margin-left: 0.25in;">
				<strong>2013</strong>: Nissan hat den Leaf zu einem autonom fahrenden Prototypen umgebaut.</li>
			<li style="margin-left: 0.25in;">
				<strong>2014</strong>: Induct Technology bringt den Acht-Sitzer &ldquo;Navia Shuttle&rdquo; als erstes kommerziell erh&auml;ltliches selbstfahrendes Fahrzeug auf den Markt.</li>
			<li style="margin-left: 0.25in;">
				<strong>2016</strong>: Tesla stattet seit 2014 die S-Klasse mit dem &ldquo;Autopiloten&rdquo; aus, der seit Januar 2016 ein autonomes Einparken ohne Fahrer erlaubt.</li>
		</ul>
	</body>
<p>
  <span style="font-size:12px;">(Quelle: Wikipedia; http://i.telegraph.co.uk/multimedia/archive/02789/Navia-shuttle_2789447b.jpg, http://viac.vislab.it)</span>
</p>
<p style="text-align: center;">
  <a href="http://innoz.de">mehr Informationen &gt;&gt;&gt;</a><a> </a>
</p>
<p>
  <a> </a><a> </a>
</p>
```

**Comment by kjoscha** [comment]
kleine ANmerkung: Dieser "mehr Inormationen"-Link war nur ein Beispiel von mir und verlinkt auf die InnoZ-Homepage. Den hast du bisher immer drin gelassen. Wäre ja cool, da auf spezifische Webseiten zu verweisen. Und du kannst  natürlich auch [Text verlinken](www.example.com)...

**Comment by super-helgi** [comment]
Hi Joscha,
ich melde mich mal zurück bei GitHub, weil ich mich gerade mal durch die Pop-ups für Flow Management geklickt habe und bevor ich's vergesse, sende ich Dir schon mal ein paar Korrekturanfragen (für alle gilt, dass der Link "mehr Info.." weg kann, aber die Links aktiv sein können): 
- [ ] ID 101: Die Grafik ist zerschossen - da muss ich noch mal morgen die Grafik checken; 
- [ ] ID 103:  Die ersten beiden Sätze nicht als Bullet-Points, sondern als Fließtext hintereinander weg; Jahreszahlen fett; Unter die Grafik bitte Folgendes setzen: Wertpotenzial des Connected Car Package - Listenpreis vs. Optionsverkäufe, Quelle: http://www.strategyand.pwc.com/reports/connected-car-2016-study; 
- [ ] ID 104: Überschrift grün machen, Bei ITS-Standards ist ein Punkt dazwischen; Bildunterschrift ergänzen: ...Korridor, Quelle: www.c-its-korridor.de
- [ ] ID 105: Überschrift ergänzen: eBusse und Ladesysteme; Bildunterschriften ergänzen: TOSA Bus in Genf       Primove-Ladesystem von Bombardier
- [ ] ID107: Zitat in kleinerer Schrift (wie die andere Schrift, aber fett); Name ohne Klammern und auch kleiner; Bildunterschriften ergänzen: ...Campus, Quelle: InnoZ; ....Charger, Quelle: www.pluglesspower.com; Die Quellen sind die von ITS
- [ ] ID 108: Überschrift angleichen: Recharging-Lanes
- [ ] ID 109: Bildunterschriften ergänzen: PostAuto-SmartShuttle in Sion, Quelle: heise online/Sperlich; Olli, Quelle: InnoZ; Erster Navya-Shuttle 2014, Quelle: The Telegraph --> Das Olli-Bild muss noch durch ein eigenes ergänzt werden!
- [ ] ID 110:  Bildunterschriften ergänzen: eMCube Wolfsburg, Quelle: InnoZ
- [ ] ID 201: Spurhalteassistent, Foto: in.pro
- [ ] ID 203: Überschrift ändern: Autonome Elektroautos, das Bild finde ich nicht mehr, daher sende ich morgen ein neues; die Unterschrift wird dann lauten: Tesla Autopilot; Quelle: http://telematicswire.net/tesla-responds-to-the-criticism-of-autopilot/
- [ ] ID 204: Der Text ist noch der von den Test-Autos; Bildunterschriften ergänzen: esla parkt ungünstig, Quelle: Jared Davis Overton, roadandtrack.com; Tesla nach tödlichem Unfall, Quelle: Nytimes.com/ Reuters, Google car ist zu langsam, Quelle: techradar.com
- [ ] ID 206: Bildunterschriften ergänzen: Der Lutz Pathfinder in Milton Keynes, Quelle: autocar.co.uk
....Rest kommt nach...
- [ ] ID 210: Spurhalteassistent, Foto: in.pro

**Comment by kjoscha** [comment]
@super-helgi 

>  ID 101: Die Grafik ist zerschossen - da muss ich noch mal morgen die Grafik checken; 

Das war ja eine PP-Grafik, die ich sich in Libre Office vermutlich etwas verzerrt. Am besten schickst du mir einen Screenshot der fertigen Grafik.

**Comment by kjoscha** [comment]
> Bildunterschrift ergänzen: ...Korridor, Quelle: www.c-its-korridor.de

ist doch schon dabei, oder?!

**Comment by kjoscha** [comment]
nee quatsch, schon verstanden mit der Bildunterschrift

**Comment by kjoscha** [comment]
>  ID 204: Der Text ist noch der von den Test-Autos

Kannst du mir den richtigen nochmal bitte schicken?
